# Generated by Django 2.2.3 on 2019-08-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Form Message', 'verbose_name_plural': 'Contact Form Messages'},
        ),
    ]
