# Generated by Django 2.2.3 on 2019-08-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipaddress',
            field=models.CharField(max_length=150),
        ),
    ]
